DSND-1902: Upgrade structured logging
companieshouse/company-appointments.api.ch.gov.uk pull request #124
Opened 2023-08-17 10:43 UTC by johncook-ch

* Added a `DataMapHolder` class to store a `DataMapHolder.Builder` instance that captures log data during message processing.
* Added a `String DataMapHolder.getRequestId()` to access the request ID used for logging
* Updated the `RequestLoggingInterceptor` to initialise the `DataMapHolder` with the request ID then ensures it is clean when processing is complete.
* Updated all logger calls to include the structured logging `DataMap` content.

The `RequestLoggingInterceptor` replaces the `StructuredLoggingFilter` described in the [Structured Logging](https://companieshouse.atlassian.net/wiki/spaces/TEAM4/pages/4253188169/Adding+Structured+Logging+to+Data+Sync+services) Confluence page.

[DSND-1902](https://companieshouse.atlassian.net/browse/DSND-1902)

2023-08-17 13:46 UTC, kinpang-CH approved these changes

2023-08-17 15:13 UTC, sthompsonCH approved these changes

2023-08-18 08:59 UTC, cgregoryCH requested changes
ResourceChangedApiService, needs a request ID on its api client as well as logMaps in its log statements.

2023-08-18 08:59 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
>          } catch (DataAccessException ex) {
Line 169 has a debug log with no logMap

2023-08-18 08:59 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
>          } catch (DataAccessException ex) {
Line 201 debug log with no logMap

2023-08-18 08:59 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/company_appointments/api/CompanyMetricsApiService.java
>          PrivateCompanyMetricsGet companyMetricsGet =
Log messages in this class need a logMap

2023-08-18 12:31 UTC, cgregoryCH approved these changes

2023-08-18 14:05 UTC, merged