Adding New CorsFilter from api-security-java to the web service
companieshouse/company-appointments.api.ch.gov.uk pull request #167
Opened 2024-07-08 11:39 UTC by hselvakumar

2024-07-08 14:48 UTC, NeilShadrach requested changes

2024-07-08 14:48 UTC, NeilShadrach commented on pom.xml
> +        <api-security-java.version>2.0.5</api-security-java.version>
Duplicates L30

2024-07-08 14:49 UTC, bcullerton commented on pom.xml
> +        </dependency>
Is this needed with the import above?

2024-07-08 14:51 UTC, NeilShadrach requested changes

2024-07-08 14:51 UTC, NeilShadrach commented on pom.xml
> +            <artifactId>spring-boot-starter-security</artifactId>
Duplicates L107

2024-07-08 14:52 UTC, hselvakumar commented on pom.xml
> +        <api-security-java.version>2.0.5</api-security-java.version>
removed now

2024-07-08 14:52 UTC, hselvakumar commented on pom.xml
> +        </dependency>
removed duplicates

2024-07-08 14:52 UTC, hselvakumar commented on pom.xml
> +            <artifactId>spring-boot-starter-security</artifactId>
removed duplicates

2024-07-08 14:55 UTC, NeilShadrach commented on src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
> +    public Config (RequestLoggingInterceptor loggingInterceptor, AuthenticationInterceptor authenticationInterceptor, FullRecordAuthenticationInterceptor fullRecordAuthenticationInterceptor){
Someone will have to explain this one to me - I see it all over the place. I thought the point of @Autowired on the private variables was that the constructor would then be generated automatically

2024-07-08 15:12 UTC, bcullerton approved these changes

2024-07-09 07:09 UTC, NeilShadrach commented on src/main/java/uk/gov/companieshouse/company_appointments/config/CorsConfiguration.java
> +@Bean
Alignment

2024-07-09 07:58 UTC, merged