DSND-1531: Update company name/status for multiple existing appointments
companieshouse/company-appointments.api.ch.gov.uk pull request #96
Opened 2023-04-14 14:58 UTC by johncook-ch

* Mapped HTTP responses codes to exceptions thrown when patching company name and status
* Added a bulk update method to update company name and status in fullRecordAppointmentRepository
* Implemented CompanyAppointmentService.patchCompanyNameStatus
* Updated CompanyAppointmentService logging to use the context ID from the MDC
* Updated dependencies in the pom.xml and removed unused dependencies

[DSND-1531](https://companieshouse.atlassian.net/browse/DSND-1531)

2023-04-17 10:08 UTC, sthompsonCH approved these changes

2023-04-18 09:51 UTC, cgregoryCH requested changes
Looks great, just a few minor comments

2023-04-18 09:51 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentServiceTest.java
> +    @DisplayName("Test throw BadRequestException when updating a companies appointments when missing company status")
Display name should mention invalid status

2023-04-18 10:15 UTC, cgregoryCH approved these changes

2023-04-18 10:49 UTC, cgregoryCH approved these changes

2023-04-18 11:58 UTC, merged